name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
       
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Cache Maven dependencies
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: build-${{ hashFiles('pom.xml') }}
        restore-keys: |
          build-

    - name: Build with Maven
      run: mvn --batch-mode -show-version --errors package
